<a href="https://colab.research.google.com/github/Anderson-Andre-P/ETL-cenipa/blob/main/ETL_Dados_de_ocorr%C3%AAncias_aeron%C3%A1uticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extração de dados

In [1]:
import pandas as pd
!pip install pandera
import pandera as pa

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandera
  Downloading pandera-0.13.4-py3-none-any.whl (122 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 KB 6.8 MB/s eta 0:00:00
Requirement already satisfied: wrapt in /usr/local/lib/python3.8/dist-packages (from pandera) (1.15.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.8/dist-packages (from pandera) (1.22.4)
Collecting typing-inspect>=0.6.0
  Downloading typing_inspect-0.8.0-py3-none-any.whl (8.7 kB)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.8/dist-packages (from pandera) (1.3.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from pandera) (23.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.8/dist-packages (from pandera) (1.10.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.2.0->pandera) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.2.0->pandera) (2022.7.1)
Collecting mypy-extensions>=0.3.0
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.8/dist-packages (from typing-inspect>=0.6.0->pandera) (4.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=1.2.0->pandera) (1.15.0)
Installing collected packages: mypy-extensions, typing-inspect, pandera
Successfully installed mypy-extensions-1.0.0 pandera-0.13.4 typing-inspect-0.8.0

In [2]:
from google.colab import files

uploaded = files.upload()

Saving ocorrencia.csv to ocorrencia.csv

## Importando Dataframe

In [132]:
uri = "/content/ocorrencia.csv"

# Limpeza de dados

In [133]:
valores_ausentes = ['**','###!','####','****','*****','NULL']

In [134]:
df = pd.read_csv(uri, sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True, na_values=valores_ausentes, engine='python', encoding='ISO-8859-1')
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
1,81030,81030,81030,81030,81030,INCIDENTE,NaN,NaN,VITÓRIA,ES,...,2022-10-09,16:20:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
3,81029,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,...,2022-10-06,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,81025,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,...,2022-10-05,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5,81019,81019,81019,81019,81019,ACIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2022-10-03,20:50:00,NÃO,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
6,81022,81022,81022,81022,81022,INCIDENTE,NaN,NaN,LOBATO,PR,...,2022-10-03,15:38:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
7,81021,81021,81021,81021,81021,ACIDENTE,NaN,NaN,NOVA BANDEIRANTES,MT,...,2022-10-02,19:00:00,NÃO,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
8,81009,81009,81009,81009,81009,INCIDENTE GRAVE,NaN,NaN,NAVIRAÍ,MS,...,2022-10-01,10:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
9,81012,81012,81012,81012,81012,INCIDENTE,NaN,NaN,LINHARES,ES,...,2022-09-30,12:20:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [135]:
df.dtypes

codigo_ocorrencia                          int64
codigo_ocorrencia1                         int64
codigo_ocorrencia2                         int64
codigo_ocorrencia3                         int64
codigo_ocorrencia4                         int64
ocorrencia_classificacao                  object
ocorrencia_latitude                       object
ocorrencia_longitude                      object
ocorrencia_cidade                         object
ocorrencia_uf                             object
ocorrencia_pais                           object
ocorrencia_aerodromo                      object
ocorrencia_dia                    datetime64[ns]
ocorrencia_hora                           object
investigacao_aeronave_liberada            object
investigacao_status                       object
divulgacao_relatorio_numero               object
divulgacao_relatorio_publicado            object
divulgacao_dia_publicacao                 object
total_recomendacoes                        int64
total_aeronaves_envolvidas                 int64
ocorrencia_saida_pista                    object
dtype: object

Como temos muitas colunas, vou excluir algumas para facilitar a análise

In [136]:
df.drop(columns = ['codigo_ocorrencia1', 
                   'codigo_ocorrencia3', 
                   'codigo_ocorrencia4', 
                   'ocorrencia_latitude', 
                   'ocorrencia_longitude', 
                   'ocorrencia_pais', 
                   'ocorrencia_pais', 
                   'investigacao_aeronave_liberada', 
                   'investigacao_status', 
                   'divulgacao_relatorio_numero', 
                   'divulgacao_relatorio_publicado', 
                   'divulgacao_dia_publicacao', 
                   'total_aeronaves_envolvidas', 
                   'ocorrencia_saida_pista'], inplace = True)

In [137]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [138]:
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,00:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
5,81019,81019,ACIDENTE,PORTO ALEGRE,RS,***,2022-10-03,20:50:00,0
6,81022,81022,INCIDENTE,LOBATO,PR,***,2022-10-03,15:38:00,0
7,81021,81021,ACIDENTE,NOVA BANDEIRANTES,MT,***,2022-10-02,19:00:00,0
8,81009,81009,INCIDENTE GRAVE,NAVIRAÍ,MS,**NI,2022-10-01,10:10:00,0
9,81012,81012,INCIDENTE,LINHARES,ES,***,2022-09-30,12:20:00,0

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6769 entries, 0 to 6768
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   codigo_ocorrencia         6769 non-null   int64
 1   codigo_ocorrencia2        6769 non-null   int64
 2   ocorrencia_classificacao  6769 non-null   object
 3   ocorrencia_cidade         6769 non-null   object
 4   ocorrencia_uf             6769 non-null   object
 5   ocorrencia_aerodromo      6769 non-null   object
 6   ocorrencia_dia            6769 non-null   datetime64[ns]
 7   ocorrencia_hora           6767 non-null   object
 8   total_recomendacoes       6769 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 476.1+ KB

In [140]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String),
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_aerodromo": pa.Column(pa.String, nullable=True),
        "ocorrencia_dia": pa.Column(pa.DateTime),
        "ocorrencia_hora": pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=False),
        "total_recomendacoes": pa.Column(pa.Int)   
    }
)

In [141]:
df.isna().sum()

codigo_ocorrencia           0
codigo_ocorrencia2          0
ocorrencia_classificacao    0
ocorrencia_cidade           0
ocorrencia_uf               0
ocorrencia_aerodromo        0
ocorrencia_dia              0
ocorrencia_hora             2
total_recomendacoes         0
dtype: int64

In [142]:
nan_values = df.loc['codigo_ocorrencia':'total_recomendacoes'].isna()
print(nan_values)

Empty DataFrame
Columns: [codigo_ocorrencia, codigo_ocorrencia2, ocorrencia_classificacao, ocorrencia_cidade, ocorrencia_uf, ocorrencia_aerodromo, ocorrencia_dia, ocorrencia_hora, total_recomendacoes]
Index: []

In [143]:
df = df.dropna()

In [144]:
# df['ocorrencia_uf'] = df['ocorrencia_uf'].replace('***', '--')
df.replace(['**', '***', '###!','####','****','*****','NULL'], pd.NA, inplace=True)

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [158]:
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  4
ocorrencia_aerodromo        2417
ocorrencia_dia                 0
ocorrencia_hora                0
total_recomendacoes            0
dtype: int64

In [146]:
# df.fillna(10, inplace=True)

In [147]:
df.head(60)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,00:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
5,81019,81019,ACIDENTE,PORTO ALEGRE,RS,<NA>,2022-10-03,20:50:00,0
6,81022,81022,INCIDENTE,LOBATO,PR,<NA>,2022-10-03,15:38:00,0
7,81021,81021,ACIDENTE,NOVA BANDEIRANTES,MT,<NA>,2022-10-02,19:00:00,0
8,81009,81009,INCIDENTE GRAVE,NAVIRAÍ,MS,**NI,2022-10-01,10:10:00,0
9,81012,81012,INCIDENTE,LINHARES,ES,<NA>,2022-09-30,12:20:00,0
10,81017,81017,INCIDENTE GRAVE,GOIÂNIA,GO,SBNV,2022-09-30,13:40:00,0
11,81006,81006,INCIDENTE,UBERLÂNDIA,MG,SBUL,2022-09-28,12:55:00,0
12,81014,81014,ACIDENTE,BOA VISTA,RR,<NA>,2022-09-27,00:00:00,0
13,81003,81003,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2022-09-26,18:30:00,0
14,81001,81001,INCIDENTE,BRAGANÇA PAULISTA,SP,SBBP,2022-09-25,20:00:00,0
15,81018,81018,ACIDENTE,LONTRAS,SC,<NA>,2022-09-24,20:05:00,0
16,81000,81000,INCIDENTE,TERESINA,PI,SBTE,2022-09-22,09:50:00,0
17,81002,81002,INCIDENTE,QUERÊNCIA,MT,<NA>,2022-09-22,18:00:00,0
18,80997,80997,INCIDENTE,GUARULHOS,SP,SBGR,2022-09-21,11:30:00,0
19,80998,80998,ACIDENTE,ENGENHEIRO CALDAS,MG,<NA>,2022-09-21,17:51:00,0
20,80993,80993,ACIDENTE,SÃO PAULO,SP,SBMT,2022-09-20,09:05:00,0
21,80995,80995,INCIDENTE,URUARÁ,PA,<NA>,2022-09-20,14:00:00,0
22,80996,80996,INCIDENTE,CAMPO LARGO,PR,<NA>,2022-09-20,18:17:00,0
23,80994,80994,INCIDENTE,CURITIBA,PR,SBCT,2022-09-19,18:40:00,0
24,80990,80990,INCIDENTE,SOCORRO,SP,**NI,2022-09-17,16:45:00,0
25,80989,80989,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-09-16,18:48:00,0
26,81007,81007,INCIDENTE,NÃO IDENTIFICADA,PR,<NA>,2022-09-16,19:40:00,0
27,80987,80987,INCIDENTE,CONFINS,MG,SBCF,2022-09-15,15:12:00,0
28,80988,80988,INCIDENTE GRAVE,CACHOEIRA DO ARARI,PA,SIEK,2022-09-15,16:20:00,0
29,81004,81004,INCIDENTE GRAVE,TERESINA,PI,SBTE,2022-09-15,12:50:00,0
30,81026,81026,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2022-09-14,01:19:00,0
31,80982,80982,INCIDENTE,SÃO PAULO,SP,SBSP,2022-09-13,11:30:00,0
32,80980,80980,ACIDENTE,LENÇÓIS PAULISTA,SP,SDLP,2022-09-11,17:00:00,0
33,80981,80981,INCIDENTE,CANTÁ,RR,SWPD,2022-09-11,13:30:00,0
34,80969,80969,INCIDENTE,MARABÁ,PA,SBMA,2022-09-10,17:45:00,0
35,80971,80971,ACIDENTE,ORIXIMINÁ,PA,<NA>,2022-09-10,13:50:00,0
36,80977,80977,INCIDENTE GRAVE,TRÊS LAGOAS,MS,<NA>,2022-09-10,12:20:00,0
37,80979,80979,ACIDENTE,ALTO ARAGUAIA,MT,<NA>,2022-09-10,22:00:00,0
38,80970,80970,INCIDENTE,BENEVIDES,PA,SNYP,2022-09-09,14:00:00,0
39,80976,80976,INCIDENTE,ITAJUBÁ,MG,SNHH,2022-09-09,15:30:00,0
40,80978,80978,ACIDENTE,SANTA HELENA DE GOIÁS,GO,<NA>,2022-09-09,15:40:00,0
41,80966,80966,ACIDENTE,JUIZ DE FORA,MG,SBJF,2022-09-08,20:10:00,0
42,80955,80955,INCIDENTE,CUIABÁ,MT,SBCY,2022-09-06,17:40:00,0
43,80961,80961,ACIDENTE,MONTE SANTO,BA,<NA>,2022-09-06,13:30:00,0
44,80972,80972,INCIDENTE,VÁRZEA GRANDE,MT,SBCY,2022-09-06,15:37:00,0
45,80974,80974,INCIDENTE,PORTO SEGURO,BA,SBPS,2022-09-06,16:50:00,0
46,80958,80958,INCIDENTE,MONTES CLAROS,MG,SBMK,2022-09-05,20:40:00,0
47,80975,80975,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-09-04,17:07:00,0
48,80954,80954,ACIDENTE,NAVEGANTES,SC,SBNF,2022-09-02,11:40:00,0
49,80963,80963,INCIDENTE,CURITIBA,PR,SBCT,2022-09-02,23:03:00,0
50,80968,80968,INCIDENTE,TEFÉ,AM,SBTF,2022-09-02,22:28:00,0
51,80973,80973,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2022-09-02,23:20:00,0
52,80952,80952,ACIDENTE,ELDORADO DO SUL,RS,SSMK,2022-09-01,18:00:00,0
53,80951,80951,INCIDENTE GRAVE,ASSIS,SP,SNAX,2022-08-31,18:45:00,0
54,80960,80960,INCIDENTE,CAMPINAS,SP,SBKP,2022-08-31,16:09:00,0
55,80985,80985,INCIDENTE,CAMPINAS,SP,SBKP,2022-08-31,16:09:00,0
57,80956,80956,INCIDENTE,FORTALEZA,CE,SBFZ,2022-08-29,12:04:00,0
58,80940,80940,ACIDENTE,RIBAS DO RIO PARDO,MS,<NA>,2022-08-28,20:30:00,0
59,80945,80945,ACIDENTE,PARÁ DE MINAS,MG,SNPA,2022-08-28,20:00:00,0
60,80948,80948,INCIDENTE,CURITIBA,PR,SBCT,2022-08-28,12:30:00,0

In [148]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,00:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,<NA>,2010-01-04,17:30:00,0
6766,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,<NA>,2010-01-03,12:00:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0

In [149]:
df.loc[[5, 12, 6765]]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,81019,81019,ACIDENTE,PORTO ALEGRE,RS,<NA>,2022-10-03,20:50:00,0
12,81014,81014,ACIDENTE,BOA VISTA,RR,<NA>,2022-09-27,00:00:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,<NA>,2010-01-04,17:30:00,0

In [150]:
df.loc[df.ocorrencia_cidade == 'ITAJUBÁ']

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
39,80976,80976,INCIDENTE,ITAJUBÁ,MG,SNHH,2022-09-09,15:30:00,0
606,80305,80305,INCIDENTE,ITAJUBÁ,MG,SNHH,2021-09-21,14:15:00,0
3799,53010,53010,INCIDENTE,ITAJUBÁ,MG,SNHH,2014-12-15,13:30:00,0
4428,50271,50271,INCIDENTE,ITAJUBÁ,MG,<NA>,2013-11-08,20:15:00,0
5053,46626,46626,INCIDENTE,ITAJUBÁ,MG,SNHH,2012-11-29,19:32:00,0

# Transformação de dados

In [152]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,00:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,<NA>,2010-01-04,17:30:00,0
6766,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,<NA>,2010-01-03,12:00:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0

In [155]:
df.loc[21:27]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
21,80995,80995,INCIDENTE,URUARÁ,PA,<NA>,2022-09-20,14:00:00,0
22,80996,80996,INCIDENTE,CAMPO LARGO,PR,<NA>,2022-09-20,18:17:00,0
23,80994,80994,INCIDENTE,CURITIBA,PR,SBCT,2022-09-19,18:40:00,0
24,80990,80990,INCIDENTE,SOCORRO,SP,**NI,2022-09-17,16:45:00,0
25,80989,80989,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-09-16,18:48:00,0
26,81007,81007,INCIDENTE,NÃO IDENTIFICADA,PR,<NA>,2022-09-16,19:40:00,0
27,80987,80987,INCIDENTE,CONFINS,MG,SBCF,2022-09-15,15:12:00,0

In [159]:
filtro_ocorrencia_aerodromo = df.ocorrencia_aerodromo.isnull()
filtro_ocorrencia_uf = df.ocorrencia_uf.isna()
df.loc[filtro_ocorrencia_aerodromo & filtro_ocorrencia_uf]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
320,80631,80631,INCIDENTE,NÃO IDENTIFICADA,<NA>,<NA>,2022-04-04,11:15:00,0
4541,49474,49474,ACIDENTE,ÁGUAS INTERNACIONAIS,<NA>,<NA>,2013-09-02,02:54:00,0

In [167]:
# ocorrências acontecidas nos dias 01 a 15 de Abril de 2021
filtro_ano = df.ocorrencia_dia.dt.year == 2021
filtro_mes = df.ocorrencia_dia.dt.month == 4
filtro_dia_inicio = df.ocorrencia_dia.dt.day > 1 
filtro_dia_fim = df.ocorrencia_dia.dt.day < 15
df.loc[filtro_ano & filtro_mes & filtro_dia_inicio & filtro_dia_fim]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
838,80021,80021,INCIDENTE,MONTES CLAROS,MG,<NA>,2021-04-14,17:35:00,0
839,80095,80095,INCIDENTE,RECIFE,PE,SBRF,2021-04-14,22:07:00,0
840,80020,80020,INCIDENTE,VITÓRIA,ES,<NA>,2021-04-13,16:30:00,0
841,80022,80022,INCIDENTE,GOIANÁ,MG,SBZM,2021-04-13,16:06:00,0
842,80030,80030,INCIDENTE,SALVADOR,BA,SBSV,2021-04-13,10:10:00,0
843,80032,80032,INCIDENTE GRAVE,SANTA ROSA DO PURUS,AC,SSRA,2021-04-13,17:15:00,0
844,80019,80019,ACIDENTE,NOVA MUTUM,MT,<NA>,2021-04-12,11:00:00,0
845,80029,80029,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2021-04-12,20:24:00,0
846,80031,80031,INCIDENTE GRAVE,TRÊS PONTAS,MG,<NA>,2021-04-11,19:30:00,0
847,80017,80017,INCIDENTE GRAVE,GOIÂNIA,GO,**NI,2021-04-09,13:00:00,0
848,80028,80028,INCIDENTE,BRASÍLIA,DF,SBBR,2021-04-09,18:32:00,0
849,80015,80015,INCIDENTE,VITÓRIA,ES,SBVT,2021-04-08,11:03:00,0
850,80018,80018,INCIDENTE,VITÓRIA,ES,SBVT,2021-04-08,19:05:00,0
851,80027,80027,INCIDENTE,PORTO ALEGRE,RS,SBPA,2021-04-07,19:47:00,0
852,80014,80014,INCIDENTE GRAVE,RIO VERDE,GO,SWLC,2021-04-06,17:50:00,0
853,80026,80026,INCIDENTE,MANAUS,AM,SBEG,2021-04-04,08:31:00,0